# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

lane :tests do |options|
  run_tests(devices: ["iPhone 11"],
  scheme: options[:schemeToChange])
end

lane :build do
    build_app(
    scheme: "Calculator Project",
    export_method: "development",
    export_options: { compileBitcode: false }
  )
end

lane :testlab do
  sh("cd Users/runner/Library/Developer/Xcode/DerivedData/Calculator_Project-csmqofdtarftncdelerzvhiigscb/Build/Products/ && zip -r ~/build_products.zip .")

  firebase_test_lab_ios_xctest(
    gcp_project: 'calculator-project-50cf6',
    app_path: '~/build_products.zip',
    skip_validation: true,
    oath_key_file_path: '~/firebase-key.json',
    devices: [
      {
        ios_model_id: 'iphone8',
        ios_version_id: '14.7',
        locale: 'en_US',
        orientation: 'portrait'
      }
    ]
  )
end