# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

lane :tests do |options|
  run_tests(devices: ["iPhone 11"],
  scheme: options[:schemeToChange])
end

lane :build do
    build_app(
    scheme: "Calculator Project",
    export_method: "development",
    export_options: { compileBitcode: false }
  )
end